# -*- coding: utf-8 -*-
"""Bono - MM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7L0i9VR1hhmt5ZRZ4fLuhtpZHKC_m_P
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import sph_harm

theta = np.linspace(0, np.pi, 300)
phi = np.linspace(0, 2*np.pi, 300)

theta, phi = np.meshgrid(theta, phi)

l = 2
m = 0

# Armónico esférico
Y = sph_harm(m, l, phi, theta).real

# Gráfica
plt.figure(figsize=(9, 4.5))

plt.contourf(phi, theta, Y, levels=100)
plt.colorbar(label=r'$Y_{\ell m}(\theta,\phi)$')

plt.xlabel(r'$\phi$')
plt.ylabel(r'$\theta$')
plt.title(r'Patrón dominado por multipolos bajos: $\ell=2$, $m=0$')

plt.xticks(
    [0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi],
    [r'$0$', r'$\pi/2$', r'$\pi$', r'$3\pi/2$', r'$2\pi$']
)

plt.yticks(
    [0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi],
    [r'$0$', r'$\pi/4$', r'$\pi/2$', r'$3\pi/4$', r'$\pi$']
)

plt.savefig('armonicos_bajos.png', dpi=300, bbox_inches='tight')

plt.show()

l = 12
m = 6

# Armónico esférico
Y = sph_harm(m, l, phi, theta).real

# Gráfica
plt.figure(figsize=(9, 4.5))

plt.contourf(phi, theta, Y, levels=100)
plt.colorbar(label=r'$Y_{\ell m}(\theta,\phi)$')

plt.xlabel(r'$\phi$')
plt.ylabel(r'$\theta$')
plt.title(r'Patrón dominado por multipolos altos: $\ell=12$, $m=6$')

plt.xticks(
    [0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi],
    [r'$0$', r'$\pi/2$', r'$\pi$', r'$3\pi/2$', r'$2\pi$']
)

plt.yticks(
    [0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi],
    [r'$0$', r'$\pi/4$', r'$\pi/2$', r'$3\pi/4$', r'$\pi$']
)

plt.savefig('armonicos_altos.png', dpi=300, bbox_inches='tight')

plt.show()

from scipy.special import yv

x = np.linspace(0.01, 20, 1000)

# Funciones de Neumann N0, N1 y N2
N0 = yv(0, x)
N1 = yv(1, x)
N2 = yv(2, x)

# Gráfica
plt.figure(figsize=(8, 5))

plt.plot(x, N0, label=r'$N_0(x)$')
plt.plot(x, N1, label=r'$N_1(x)$')
plt.plot(x, N2, label=r'$N_2(x)$')

plt.axhline(0, color='black', linewidth=0.8)

plt.xlabel(r'$x$')
plt.ylabel(r'$N_n(x)$')
plt.title('Funciones de Neumann')
plt.legend()
plt.grid(True)

plt.ylim(-2, 1)

plt.savefig('neumann.png', dpi=300, bbox_inches='tight')

plt.show()